# Generated by Django 3.2.5 on 2021-07-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gained',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
