# Generated by Django 3.2.5 on 2021-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_gained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ready_to_distribute',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
    ]
