# Generated by Django 4.2.3 on 2023-07-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_ready_to_distribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ready_to_distribute",
            field=models.CharField(
                choices=[("no", "No"), ("yes", "Yes")], default="no", max_length=10
            ),
        ),
    ]
